#!/usr/local/bin/zsh

# Color
BLUE='\033[0;34m'
DEF='\033[0m'

echo -e "${BLUE}...Install node packages..."
echo -e "${BLUE}Last updated: 2019/09/24${DEF}"

# update self
npm i -g npm

# install dependents
npm i -g \
  eslint \
  eslint-config-airbnb-base \
  eslint-plugin-import \
  eslint-plugin-react \
  babel-eslint \
  surge \
  favicon-emoji \
  chromenu \
  now \
  prisma \
  @angular/cli \
  typescript \
  tslint

echo -e "${BLUE}List up what you installed global${DEF}"
npm ls -g --depth 0
