#!/usr/local/bin/zsh

# Color
BLUE='\033[0;34m'
DEF='\033[0m'

echo -e "${BLUE}...Install node packages..."
echo -e "${BLUE}Last updated: 2018/10/10${DEF}"

# update self
npm i -g npm

# install dependents
npm i -g \
  eslint \
  eslint-config-airbnb-base \
  eslint-plugin-import \
  eslint-plugin-react \
  babel-eslint \
  surge \
  electron \
  chromenu \
  elm \
  elm-format \
  create-react-app \
  now \
  now-compose

# use yarn instead of npm
# because of `npm i -g mstdn` do not work for me
yarn global add mstdn --prefix /usr/local

echo -e "${BLUE}List up what you installed global${DEF}"
npm ls -g --depth 0
